/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cliente;
import Model.Funcionario;
import Model.Produto;
import Model.Venda;
import Model.VendasProduto;
import Util.Converte;
import Util.Mascara;
import dao.ClienteDAO;
import dao.FuncionarioDAO;
import dao.ProdutoDAO;
import dao.VendaDAO;
import dao.VendasProdutoDAO;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tegon Faria
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    DecimalFormat df = new DecimalFormat("##,##");
    ClienteDAO ClienteDAO = new ClienteDAO();
    Cliente cliente = new Cliente();
    ArrayList<Cliente> listaCliente = new ArrayList<>();
    ProdutoDAO ProdutoDAO = new ProdutoDAO();
    Produto produto = new Produto();
    ArrayList<Produto> listaProduto = new ArrayList<>();
    FuncionarioDAO FuncionarioDAO = new FuncionarioDAO();
    Funcionario funcionario = new Funcionario();
    ArrayList<Funcionario> listaFuncionario = new ArrayList<>();
    Venda venda = new Venda();
    VendaDAO VendaDAO = new VendaDAO();
    VendasProduto vendasProduto = new VendasProduto();
    VendasProdutoDAO vendasProdutoDAO = new VendasProdutoDAO();
    ArrayList<VendasProduto> listaVp = new ArrayList<>();


    public TelaPrincipal() {
        initComponents();
        setMask();
        tfValorTotal.setText("0,00");
        tfDescontoCompra.setText("0");
        listarClientes();
        listarFuncionarioVendedor();
        limpa();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutosVenda = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lbCodProdVenda = new javax.swing.JLabel();
        tfCodProdVenda = new javax.swing.JTextField();
        tfDescProdVenda = new javax.swing.JTextField();
        lbDescProdVenda = new javax.swing.JLabel();
        tfMarcaProdVenda = new javax.swing.JTextField();
        lbMarcaProdVenda = new javax.swing.JLabel();
        tfQtdProdVenda = new javax.swing.JTextField();
        lbQtdProdVenda = new javax.swing.JLabel();
        lbValorProdVenda = new javax.swing.JLabel();
        btAdicionaCarrinho = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btFinalizaVenda = new javax.swing.JButton();
        cbFuncionarioVenda = new javax.swing.JComboBox<>();
        lbFuncionarioVenda = new javax.swing.JLabel();
        tfValorProd = new javax.swing.JFormattedTextField();
        tfCustoProd = new javax.swing.JFormattedTextField();
        lbValorProdVenda1 = new javax.swing.JLabel();
        tfDataVenda = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btrefresh = new javax.swing.JButton();
        tfCPFCliente = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btNovoVenda = new javax.swing.JButton();
        btAlteraVenda = new javax.swing.JButton();
        cbClienteVenda = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        tfValorTotal = new javax.swing.JFormattedTextField();
        tfDescontoCompra = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfBuscaVenda = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btCliente = new javax.swing.JButton();
        btFunc = new javax.swing.JButton();
        btProduto = new javax.swing.JButton();
        btVendas = new javax.swing.JButton();
        btCargo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Morpheus");
        setBackground(new java.awt.Color(57, 57, 57));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setName("Morpheus"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Prod", "Nome Produto", "Quantidade", "Valor Un.", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutosVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutosVendaMouseClicked(evt);
            }
        });
        tbProdutosVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbProdutosVendaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbProdutosVenda);
        if (tbProdutosVenda.getColumnModel().getColumnCount() > 0) {
            tbProdutosVenda.getColumnModel().getColumn(0).setMinWidth(90);
            tbProdutosVenda.getColumnModel().getColumn(0).setPreferredWidth(90);
            tbProdutosVenda.getColumnModel().getColumn(0).setMaxWidth(90);
            tbProdutosVenda.getColumnModel().getColumn(2).setMinWidth(70);
            tbProdutosVenda.getColumnModel().getColumn(2).setPreferredWidth(70);
            tbProdutosVenda.getColumnModel().getColumn(2).setMaxWidth(70);
            tbProdutosVenda.getColumnModel().getColumn(3).setMinWidth(90);
            tbProdutosVenda.getColumnModel().getColumn(3).setPreferredWidth(90);
            tbProdutosVenda.getColumnModel().getColumn(3).setMaxWidth(90);
            tbProdutosVenda.getColumnModel().getColumn(4).setMinWidth(90);
            tbProdutosVenda.getColumnModel().getColumn(4).setPreferredWidth(90);
            tbProdutosVenda.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Produto"));

        lbCodProdVenda.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbCodProdVenda.setText("Codigo do Produto");

        tfCodProdVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodProdVendaFocusLost(evt);
            }
        });
        tfCodProdVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodProdVendaActionPerformed(evt);
            }
        });
        tfCodProdVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodProdVendaKeyPressed(evt);
            }
        });

        tfDescProdVenda.setEditable(false);

        lbDescProdVenda.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbDescProdVenda.setText("Descrição ");

        tfMarcaProdVenda.setEditable(false);

        lbMarcaProdVenda.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbMarcaProdVenda.setText("Marca");

        lbQtdProdVenda.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbQtdProdVenda.setText("Quantidade");

        lbValorProdVenda.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbValorProdVenda.setText("Valor");

        btAdicionaCarrinho.setText("Adicionar");
        btAdicionaCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionaCarrinhoActionPerformed(evt);
            }
        });

        btFinalizaVenda.setText("Salvar");
        btFinalizaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizaVendaActionPerformed(evt);
            }
        });

        lbFuncionarioVenda.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbFuncionarioVenda.setText("Funcionario");

        tfValorProd.setEditable(false);

        tfCustoProd.setEditable(false);

        lbValorProdVenda1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbValorProdVenda1.setText("Custo");

        jLabel1.setText("Data:");

        btrefresh.setText("⟳");
        btrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrefreshActionPerformed(evt);
            }
        });

        tfCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCPFClienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel3.setText("CPF Cliente");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel4.setText("Nome Cliente");

        btNovoVenda.setText("Novo");
        btNovoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoVendaActionPerformed(evt);
            }
        });

        btAlteraVenda.setText("Altera");
        btAlteraVenda.setEnabled(false);
        btAlteraVenda.setRolloverEnabled(true);
        btAlteraVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlteraVendaActionPerformed(evt);
            }
        });

        cbClienteVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbClienteVendaFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("/");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbCodProdVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfCodProdVenda))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDescProdVenda)
                                    .addComponent(tfDescProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMarcaProdVenda)
                                    .addComponent(tfMarcaProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfQtdProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbQtdProdVenda))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbValorProdVenda1)
                                    .addComponent(tfCustoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbValorProdVenda)
                                    .addComponent(tfValorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAdicionaCarrinho, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cbClienteVenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFuncionarioVenda)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cbFuncionarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btrefresh))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btNovoVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAlteraVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btFinalizaVenda)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbMarcaProdVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMarcaProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbDescProdVenda)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbCodProdVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDescProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbQtdProdVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQtdProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbValorProdVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbValorProdVenda1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCustoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(btAdicionaCarrinho)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(lbFuncionarioVenda)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFuncionarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btrefresh))))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFinalizaVenda)
                    .addComponent(btNovoVenda)
                    .addComponent(btAlteraVenda)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        lbTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTotal.setText("Total:");

        tfValorTotal.setEditable(false);
        tfValorTotal.setText("0");
        tfValorTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        tfDescontoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescontoCompraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel2.setText("Desconto");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca venda"));

        tfBuscaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscaVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfBuscaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfBuscaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDescontoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDescontoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(lbTotal)
                            .addComponent(tfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 690));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Ativo 1Cliente.png"))); // NOI18N
        btCliente.setMaximumSize(new java.awt.Dimension(100, 100));
        btCliente.setMinimumSize(new java.awt.Dimension(100, 100));
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        btFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Ativo 2Funcionario.png"))); // NOI18N
        btFunc.setMaximumSize(new java.awt.Dimension(100, 100));
        btFunc.setMinimumSize(new java.awt.Dimension(100, 100));
        btFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncActionPerformed(evt);
            }
        });

        btProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Ativo 3Produto.png"))); // NOI18N
        btProduto.setMaximumSize(new java.awt.Dimension(100, 100));
        btProduto.setMinimumSize(new java.awt.Dimension(100, 100));
        btProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutoActionPerformed(evt);
            }
        });

        btVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Ativo 2Venda.png"))); // NOI18N
        btVendas.setMaximumSize(new java.awt.Dimension(100, 100));
        btVendas.setMinimumSize(new java.awt.Dimension(100, 100));
        btVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendasActionPerformed(evt);
            }
        });

        btCargo.setText("Cargos");
        btCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btCargo)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        TelaCliente tcc = new TelaCliente();
        tcc.setLocationRelativeTo(rootPane);
        tcc.setVisible(true);
    }//GEN-LAST:event_btClienteActionPerformed

    private void btFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncActionPerformed
        TelaFuncionario tcf = new TelaFuncionario();
        tcf.setLocationRelativeTo(rootPane);
        tcf.setVisible(true);
    }//GEN-LAST:event_btFuncActionPerformed

    private void btProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutoActionPerformed
        TelaProdutos tcp = new TelaProdutos();
        tcp.setLocationRelativeTo(rootPane);
        tcp.setVisible(true);
    }//GEN-LAST:event_btProdutoActionPerformed

    private void btVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendasActionPerformed
        TelaVendas tv = new TelaVendas();
        tv.setLocationRelativeTo(rootPane);
        tv.setVisible(true);
    }//GEN-LAST:event_btVendasActionPerformed

    private void btCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargoActionPerformed
        TelaCargo tc = new TelaCargo();
        tc.setLocationRelativeTo(rootPane);
        tc.setVisible(true);
    }//GEN-LAST:event_btCargoActionPerformed

    private void tbProdutosVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbProdutosVendaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            DefaultTableModel modelo = (DefaultTableModel) tbProdutosVenda.getModel();
            int row = tbProdutosVenda.getSelectedRow();
            modelo.removeRow(row);
            tbProdutosVenda.setModel(modelo);
            somaValorTotal();
        }
    }//GEN-LAST:event_tbProdutosVendaKeyPressed

    private void btFinalizaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizaVendaActionPerformed
        double valorTotal = Converte.textoToValue(tfValorTotal.getText());
        int desconto = 0;
        if(tfDataVenda.getText().equals("__/__/____")){
            JOptionPane.showMessageDialog(rootPane, "Existem campos necessarios não preenchidos");
        }else{
            if(tfDescontoCompra.getText().isEmpty()){
                desconto = 0;
            }else{
                desconto = Integer.parseInt(tfDescontoCompra.getText());
            }
            cliente = (Cliente) cbClienteVenda.getModel().getSelectedItem();
            funcionario = (Funcionario) cbFuncionarioVenda.getModel().getSelectedItem();
            String data = tfDataVenda.getText();
            //------------------------------------------------------------------------//
            venda = new Venda(valorTotal, desconto, cliente, data, funcionario);
            int codigoVenda = VendaDAO.create(venda);
            //-----------------------------------------------------------------------//
            DefaultTableModel model = (DefaultTableModel) tbProdutosVenda.getModel();
            int cont = model.getRowCount();
            for(int i = 0; i<cont; i++){
                int codProduto = (int) model.getValueAt(i, 0);
                int qtdItVenda = (int) model.getValueAt(i, 2);
                double valorTotalProd = (double) model.getValueAt(i, 4);
                vendasProduto = new VendasProduto(codProduto, codigoVenda, valorTotalProd, qtdItVenda);
                produto = ProdutoDAO.findById(vendasProduto.getProduto());
                produto.setQuantidade(produto.getQuantidade() - qtdItVenda);
                ProdutoDAO.update(produto);
                
                vendasProdutoDAO.craete(vendasProduto);
            }
            limpa();
        }
        
    }//GEN-LAST:event_btFinalizaVendaActionPerformed

    private void btAdicionaCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionaCarrinhoActionPerformed
        try{
            produto = ProdutoDAO.findById(Integer.parseInt(tfCodProdVenda.getText()));
            if(tfQtdProdVenda.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Campo não preenchido");
            }else if(Integer.parseInt(tfQtdProdVenda.getText()) > produto.getQuantidade()){
                JOptionPane.showMessageDialog(rootPane, "Quantidade indisponivel");
            }
            else{
                DefaultTableModel modelo = (DefaultTableModel) tbProdutosVenda.getModel();
                int cont = modelo.getRowCount();
                int qtdVenda = Integer.parseInt(tfQtdProdVenda.getText());
                for(int i = 0 ; i > cont; i++){
                    modelo.setNumRows(0);
                }

                modelo.addRow(new Object[]{
                    produto.getCodigo(),
                    produto.getDescricao(),
                    qtdVenda,
                    produto.getValor(),
                    qtdVenda*produto.getValor()
                });
            }
            aplicaDesconto();
            tfCodProdVenda.setText("");
            tfDescProdVenda.setText("");
            tfMarcaProdVenda.setText("");
            tfQtdProdVenda.setText("");
            tfCustoProd.setText("0,00");
            tfValorProd.setText("0,00");
            tfCodProdVenda.requestFocus();
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane, "Não Foi possivel Adiconar ao carrinho");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(rootPane, "Digite um codigo para realizar a operação");
        }
        
    }//GEN-LAST:event_btAdicionaCarrinhoActionPerformed

    private void tfDescontoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescontoCompraActionPerformed
        aplicaDesconto();
    }//GEN-LAST:event_tfDescontoCompraActionPerformed

    private void btrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrefreshActionPerformed
        listarClientes();
        listarFuncionarioVendedor();
    }//GEN-LAST:event_btrefreshActionPerformed

    private void tfCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCPFClienteActionPerformed
        cliente = ClienteDAO.find(tfCPFCliente.getText());
        cbClienteVenda.getModel().setSelectedItem(cliente);
        
    }//GEN-LAST:event_tfCPFClienteActionPerformed

    private void btNovoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoVendaActionPerformed
        int rows = tbProdutosVenda.getRowCount();
        if(rows>0){
            int op = JOptionPane.showConfirmDialog(rootPane, "Existe um pedido em andamento, deseja cancelar?", "Aviso", JOptionPane.WARNING_MESSAGE);
            if(op == 0){
                limpa();
                tfBuscaVenda.setText("");
            }
        }else{
            limpa();
            tfBuscaVenda.setText("");

        }
        
    }//GEN-LAST:event_btNovoVendaActionPerformed

    private void tfBuscaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscaVendaActionPerformed
        int rows = tbProdutosVenda.getRowCount();
        if(rows>0){
            int op = JOptionPane.showConfirmDialog(rootPane, "Existe um pedido em andamento, deseja cancelar?", "Aviso", JOptionPane.WARNING_MESSAGE);
            if(op == 0){
                buscaVenda();
            }
        }else{
            buscaVenda();
        }
    }//GEN-LAST:event_tfBuscaVendaActionPerformed

    private void cbClienteVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbClienteVendaFocusLost
        cliente = (Cliente) cbClienteVenda.getModel().getSelectedItem();
        tfCPFCliente.setText(cliente.getCpf());
    }//GEN-LAST:event_cbClienteVendaFocusLost

    private void tfCodProdVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodProdVendaFocusLost
        try{
            produto = ProdutoDAO.findById(Integer.parseInt(tfCodProdVenda.getText()));
            tfDescProdVenda.setText(produto.getDescricao());
            tfMarcaProdVenda.setText(produto.getMarca());
            tfCustoProd.setText(df.format(produto.getCusto()));
            tfValorProd.setText(df.format(produto.getValor()));
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane, "Este produto não existe");
            tfCodProdVenda.requestFocus();
        } catch(NumberFormatException ex){
        }
    }//GEN-LAST:event_tfCodProdVendaFocusLost

    private void tfCodProdVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodProdVendaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfQtdProdVenda.requestFocus();
        }
    }//GEN-LAST:event_tfCodProdVendaKeyPressed

    private void tbProdutosVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutosVendaMouseClicked
        tbProdutosVenda.requestFocus();
    }//GEN-LAST:event_tbProdutosVendaMouseClicked

    private void tfCodProdVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodProdVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodProdVendaActionPerformed

    private void btAlteraVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlteraVendaActionPerformed
        double valorTotal = Converte.textoToValue(tfValorTotal.getText());
        int desconto = 0;
        if(tfDescontoCompra.getText().isEmpty()){
            desconto = 0;
        }else{
            desconto = Integer.parseInt(tfDescontoCompra.getText());
        }
        cliente = (Cliente) cbClienteVenda.getModel().getSelectedItem();
        funcionario = (Funcionario) cbFuncionarioVenda.getModel().getSelectedItem();
        String data = tfDataVenda.getText();
        int codPedido = Integer.parseInt(tfBuscaVenda.getText());
        //------------------------------------------------------------------------//
        venda = new Venda(codPedido, valorTotal, desconto, cliente, data, funcionario);
        VendaDAO.update(venda);
        //-----------------------------------------------------------------------//
        listaVp = (ArrayList<VendasProduto>) vendasProdutoDAO.find(codPedido);
        for(VendasProduto vp: listaVp){
            produto = ProdutoDAO.findById(vp.getProduto());
            produto.setQuantidade(produto.getQuantidade() + vp.getVenProdQtd());
            ProdutoDAO.update(produto);
        }
        //------------------------------------------------------------------------//
        DefaultTableModel model = (DefaultTableModel) tbProdutosVenda.getModel();
        int cont = tbProdutosVenda.getRowCount();
        vendasProdutoDAO.delete(codPedido);
        for(int i = 0; i<cont; i++){
            int codProduto = (int) model.getValueAt(i, 0);
            int qtdItVenda = (int) model.getValueAt(i, 2);
            double valorTotalProd = (double) model.getValueAt(i, 4);
            vendasProduto = new VendasProduto(codProduto, codPedido, valorTotalProd, qtdItVenda);
            produto = ProdutoDAO.findById(vendasProduto.getProduto());
            produto.setQuantidade(produto.getQuantidade() - qtdItVenda);
            ProdutoDAO.update(produto);

            vendasProdutoDAO.craete(vendasProduto);
        }
        limpa();
        tfDataVenda.setEditable(true);
        tfBuscaVenda.setText("");
    }//GEN-LAST:event_btAlteraVendaActionPerformed

    private void setMask() {
        tfValorProd.setFormatterFactory(Mascara.getValorMask());
        tfValorTotal.setFormatterFactory(Mascara.getValorMask());
        tfCPFCliente.setFormatterFactory(Mascara.getCpfMask());
        tfDataVenda.setFormatterFactory(Mascara.getDataMask());
    }

    private void listarClientes(){
        listaCliente = (ArrayList<Cliente>) ClienteDAO.read();
        cbClienteVenda.removeAllItems();
        for(Cliente c:listaCliente){
            cbClienteVenda.addItem(c);
        }
    }
    
    private void listarFuncionarioVendedor(){
        listaFuncionario = (ArrayList<Funcionario>) FuncionarioDAO.read();
        cbFuncionarioVenda.removeAllItems();
        for(Funcionario f:listaFuncionario){
            if(f.getCargo().getNome_cargo().equals("Vendedor") && f.isAtivo() == true){
                cbFuncionarioVenda.addItem(f);
            }
        }
    }
    
    private void somaValorTotal(){
        double soma = 0, valor;
        int count = tbProdutosVenda.getRowCount();
        for (int i = 0; i<count; i++){
            valor = (double) tbProdutosVenda.getValueAt(i, 4);
            soma = soma+valor;
        }
        tfValorTotal.setText(df.format(soma));
    }
    
    private void aplicaDesconto(){
        try{
            somaValorTotal();
            double desconto = Double.parseDouble(tfDescontoCompra.getText())/100;
            double valor = Converte.textoToValue(tfValorTotal.getText());
            valor = valor - valor*desconto;
            tfValorTotal.setText(df.format(valor));
        }catch(NumberFormatException ex){
            somaValorTotal();
        }
    }
    private void limpa(){
        tfCodProdVenda.setText("");
        tfDescProdVenda.setText("");
        tfMarcaProdVenda.setText("");
        tfQtdProdVenda.setText("");
        tfCustoProd.setText("0,00");
        tfValorProd.setText("0,00");
        //
        tfCPFCliente.setText("");
        tfDataVenda.setText("");
        tfValorTotal.setText("0,00");
        tfDescontoCompra.setText("0");
        DefaultTableModel modelo = (DefaultTableModel) tbProdutosVenda.getModel();
        modelo.setNumRows(0);
        tbProdutosVenda.setModel(modelo);
        btAlteraVenda.setEnabled(false);
        btFinalizaVenda.setEnabled(true);
        tfDataVenda.setEditable(true);
        tfCodProdVenda.requestFocus();
    }
    
    private void buscaVenda(){
        limpa();
        btAlteraVenda.setEnabled(true);
        btFinalizaVenda.setEnabled(false);
        tfDataVenda.setEditable(false);
        int cod = Integer.parseInt(tfBuscaVenda.getText());
        venda = VendaDAO.find(cod);
        tfDescontoCompra.setText(String.valueOf(venda.getDesconto()));
        tfDataVenda.setText(venda.getData_venda());
        tfCPFCliente.setText(venda.getCliente().getCpf());
        cbClienteVenda.getModel().setSelectedItem(venda.getCliente());
        cbFuncionarioVenda.getModel().setSelectedItem(venda.getVendedor());

        listaVp = (ArrayList<VendasProduto>) vendasProdutoDAO.find(cod);
        DefaultTableModel model = (DefaultTableModel) tbProdutosVenda.getModel();
        for(VendasProduto v:listaVp){
            produto = ProdutoDAO.findById(v.getProduto());

            model.addRow(new Object[]{
                produto.getCodigo(),
                produto.getDescricao(),
                v.getVenProdQtd(),
                produto.getValor(),
                v.getVenProdQtd()*produto.getValor()});
        }
        somaValorTotal();
        aplicaDesconto();
    }
    
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionaCarrinho;
    private javax.swing.JButton btAlteraVenda;
    private javax.swing.JButton btCargo;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btFinalizaVenda;
    private javax.swing.JButton btFunc;
    private javax.swing.JButton btNovoVenda;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btVendas;
    private javax.swing.JButton btrefresh;
    private javax.swing.JComboBox<Object> cbClienteVenda;
    private javax.swing.JComboBox<Object> cbFuncionarioVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCodProdVenda;
    private javax.swing.JLabel lbDescProdVenda;
    private javax.swing.JLabel lbFuncionarioVenda;
    private javax.swing.JLabel lbMarcaProdVenda;
    private javax.swing.JLabel lbQtdProdVenda;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbValorProdVenda;
    private javax.swing.JLabel lbValorProdVenda1;
    private javax.swing.JTable tbProdutosVenda;
    private javax.swing.JTextField tfBuscaVenda;
    private javax.swing.JFormattedTextField tfCPFCliente;
    private javax.swing.JTextField tfCodProdVenda;
    private javax.swing.JFormattedTextField tfCustoProd;
    private javax.swing.JFormattedTextField tfDataVenda;
    private javax.swing.JTextField tfDescProdVenda;
    private javax.swing.JFormattedTextField tfDescontoCompra;
    private javax.swing.JTextField tfMarcaProdVenda;
    private javax.swing.JTextField tfQtdProdVenda;
    private javax.swing.JFormattedTextField tfValorProd;
    private javax.swing.JFormattedTextField tfValorTotal;
    // End of variables declaration//GEN-END:variables

}
