/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cargo;
import Model.Funcionario;
import Util.Converte;
import Util.Mascara;
import dao.CargoDAO;
import dao.FuncionarioDAO;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tegon Faria
 */
public class TelaFuncionario extends javax.swing.JFrame {
    
    Funcionario func = new Funcionario();
    FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
    ArrayList<Funcionario> listaFunc = new ArrayList<Funcionario>();
    
    public TelaFuncionario() {
        initComponents();
        setMask();
        preencheCb();
        carregaFuncionario();
        tfNomeFunc.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBuscar = new javax.swing.JLabel();
        btBuscarFunc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFunc = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNomeFunc = new javax.swing.JLabel();
        tfNomeFunc = new javax.swing.JTextField();
        lbCPFFunc = new javax.swing.JLabel();
        tfCPFFunc = new javax.swing.JFormattedTextField();
        tfCelularFunc = new javax.swing.JFormattedTextField();
        lbCelFunc = new javax.swing.JLabel();
        tfDnFunc = new javax.swing.JFormattedTextField();
        lbDnFunc = new javax.swing.JLabel();
        lbDrFunc = new javax.swing.JLabel();
        tfEmailFunc = new javax.swing.JFormattedTextField();
        lbEmailFunc = new javax.swing.JLabel();
        btGravarFunc = new javax.swing.JButton();
        btAlterarFunc = new javax.swing.JButton();
        btDeletarFunc = new javax.swing.JButton();
        tfDrFunc = new javax.swing.JFormattedTextField();
        tfSalarioFunc = new javax.swing.JFormattedTextField();
        lbSalarioFunc = new javax.swing.JLabel();
        lbStatusFunc = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        cbCargo = new javax.swing.JComboBox<>();
        CheckAtivo = new javax.swing.JCheckBox();
        lbCargp = new javax.swing.JLabel();
        btLimpaBusca = new javax.swing.JButton();
        tfBuscarFunc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionarios");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBuscar.setText("Buscar:");
        jPanel1.add(lbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 16, -1, -1));

        btBuscarFunc.setText("Buscar");
        btBuscarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarFuncActionPerformed(evt);
            }
        });
        jPanel1.add(btBuscarFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        tbFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome Funcionario", "CPF", "Data Registro", "Celular", "E-mail", "Cargo", "Salario", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFuncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFunc);
        if (tbFunc.getColumnModel().getColumnCount() > 0) {
            tbFunc.getColumnModel().getColumn(0).setMinWidth(250);
            tbFunc.getColumnModel().getColumn(0).setPreferredWidth(250);
            tbFunc.getColumnModel().getColumn(0).setMaxWidth(250);
            tbFunc.getColumnModel().getColumn(1).setMinWidth(100);
            tbFunc.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbFunc.getColumnModel().getColumn(1).setMaxWidth(100);
            tbFunc.getColumnModel().getColumn(2).setMinWidth(90);
            tbFunc.getColumnModel().getColumn(2).setPreferredWidth(90);
            tbFunc.getColumnModel().getColumn(2).setMaxWidth(90);
            tbFunc.getColumnModel().getColumn(3).setMinWidth(100);
            tbFunc.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbFunc.getColumnModel().getColumn(3).setMaxWidth(100);
            tbFunc.getColumnModel().getColumn(4).setMinWidth(160);
            tbFunc.getColumnModel().getColumn(4).setPreferredWidth(160);
            tbFunc.getColumnModel().getColumn(4).setMaxWidth(160);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 47, 960, 247));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 343, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionario"));

        lbNomeFunc.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbNomeFunc.setText("Nome");

        tfNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeFuncActionPerformed(evt);
            }
        });
        tfNomeFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNomeFuncKeyPressed(evt);
            }
        });

        lbCPFFunc.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbCPFFunc.setText("CPF");

        tfCPFFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCPFFuncKeyPressed(evt);
            }
        });

        tfCelularFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCelularFuncKeyPressed(evt);
            }
        });

        lbCelFunc.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbCelFunc.setText("Celular");

        tfDnFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDnFuncActionPerformed(evt);
            }
        });
        tfDnFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDnFuncKeyPressed(evt);
            }
        });

        lbDnFunc.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbDnFunc.setText("Data de Nascimento");

        lbDrFunc.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbDrFunc.setText("Data Registro");

        tfEmailFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEmailFuncKeyPressed(evt);
            }
        });

        lbEmailFunc.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbEmailFunc.setText("E-mail");

        btGravarFunc.setText("Gravar");
        btGravarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarFuncActionPerformed(evt);
            }
        });

        btAlterarFunc.setText("Alterar");
        btAlterarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarFuncActionPerformed(evt);
            }
        });

        btDeletarFunc.setText("Deletar");
        btDeletarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarFuncActionPerformed(evt);
            }
        });

        tfDrFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDrFuncActionPerformed(evt);
            }
        });
        tfDrFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDrFuncKeyPressed(evt);
            }
        });

        tfSalarioFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalarioFuncActionPerformed(evt);
            }
        });

        lbSalarioFunc.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbSalarioFunc.setText("Salario");

        lbStatusFunc.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbStatusFunc.setText("Status");

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        cbCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbCargoKeyPressed(evt);
            }
        });

        CheckAtivo.setText("Ativo");

        lbCargp.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        lbCargp.setText("Cargos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeFunc)
                            .addComponent(tfNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCPFFunc)
                            .addComponent(tfCPFFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCelFunc)
                            .addComponent(tfCelularFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEmailFunc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDnFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDnFunc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDrFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDrFunc))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCargp)
                                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btGravarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAlterarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btDeletarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSalarioFunc)
                                    .addComponent(tfSalarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbStatusFunc)
                                    .addComponent(CheckAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbNomeFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbCPFFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCPFFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbCelFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCelularFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDnFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDrFunc)
                                    .addComponent(lbCargp, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSalarioFunc)
                                    .addComponent(lbStatusFunc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfSalarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckAtivo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDeletarFunc)
                            .addComponent(btAlterarFunc)
                            .addComponent(btGravarFunc)
                            .addComponent(btNovo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbEmailFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDnFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDrFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 300, 960, -1));

        btLimpaBusca.setText("Limpar Busca");
        btLimpaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpaBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpaBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));
        jPanel1.add(tfBuscarFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 14, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarFuncActionPerformed
        busca();
    }//GEN-LAST:event_btBuscarFuncActionPerformed

    private void tbFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFuncMouseClicked
        String padrao = "##.##";
        DecimalFormat df = new DecimalFormat(padrao);
        int row = tbFunc.getSelectedRow();
        String cpf = (String) tbFunc.getValueAt(row, 1);
        func = funcionarioDAO.find(cpf);
        //preenche campos
        tfNomeFunc.setText(func.getNome());
        tfCPFFunc.setText(func.getCpf());
        tfCelularFunc.setText(func.getCelular());
        tfEmailFunc.setText(func.getEmail());
        tfDnFunc.setText(func.getData_nascimento());
        tfDrFunc.setText(func.getRegistro());
        cbCargo.getModel().setSelectedItem(func.getCargo());
        tfSalarioFunc.setText(df.format(func.getSalario()));
        CheckAtivo.setSelected(func.isAtivo());
        
    }//GEN-LAST:event_tbFuncMouseClicked

    private void tfNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeFuncActionPerformed

    private void tfNomeFuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeFuncKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfCPFFunc.requestFocus();
        }
    }//GEN-LAST:event_tfNomeFuncKeyPressed

    private void tfCPFFuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCPFFuncKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfCelularFunc.requestFocus();
        }
    }//GEN-LAST:event_tfCPFFuncKeyPressed

    private void tfCelularFuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCelularFuncKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfEmailFunc.requestFocus();
        }
    }//GEN-LAST:event_tfCelularFuncKeyPressed

    private void tfDnFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDnFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDnFuncActionPerformed

    private void tfDnFuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDnFuncKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfDrFunc.requestFocus();
        }
    }//GEN-LAST:event_tfDnFuncKeyPressed

    private void tfEmailFuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmailFuncKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfDnFunc.requestFocus();
        }
    }//GEN-LAST:event_tfEmailFuncKeyPressed

    private void btGravarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarFuncActionPerformed
        grava();
        carregaFuncionario();
    }//GEN-LAST:event_btGravarFuncActionPerformed

    private void btAlterarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarFuncActionPerformed
        update();
        carregaFuncionario();
    }//GEN-LAST:event_btAlterarFuncActionPerformed

    private void btDeletarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarFuncActionPerformed
        deleta();
        carregaFuncionario();
    }//GEN-LAST:event_btDeletarFuncActionPerformed

    private void tfDrFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDrFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDrFuncActionPerformed

    private void tfDrFuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDrFuncKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbCargo.requestFocus();
        }
    }//GEN-LAST:event_tfDrFuncKeyPressed

    private void tfSalarioFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalarioFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSalarioFuncActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        limpa();
    }//GEN-LAST:event_btNovoActionPerformed

    private void cbCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCargoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfSalarioFunc.requestFocus();
        }
    }//GEN-LAST:event_cbCargoKeyPressed

    private void btLimpaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpaBuscaActionPerformed
        tfBuscarFunc.setText("");
        carregaFuncionario();
    }//GEN-LAST:event_btLimpaBuscaActionPerformed

    private void grava() {
        if (tfNomeFunc.getText().isEmpty() || tfCPFFunc.getText().isEmpty() || tfSalarioFunc.getText().isEmpty()
                || tfDnFunc.getText().isEmpty() || tfDrFunc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campos necessarios não preenchidos");
        } else {
            String nome = tfNomeFunc.getText();
            String cpf = tfCPFFunc.getText();
            String cel = tfCelularFunc.getText();
            String email = tfEmailFunc.getText();
            String data_nasc = tfDnFunc.getText();
            String data_registro = tfDrFunc.getText();
            Cargo cargo = null;
            cargo = (Cargo) cbCargo.getSelectedItem();
            double salario = Converte.textoToValue(tfSalarioFunc.getText());
            boolean Ativo = CheckAtivo.isSelected();
            if (funcionarioDAO.create(new Funcionario(cargo, Ativo, salario, nome, email, cpf, data_nasc, cel, data_registro))) {
                JOptionPane.showMessageDialog(rootPane, "Sucesso");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Falhou, tente novamente");
            }
        }
        limpa();
    }

    private void busca() {
        func = funcionarioDAO.find(tfBuscarFunc.getText());
        String ativo = "Inativo";
        if(func.isAtivo()){
            ativo =  "Ativo";
        }
        DefaultTableModel model = (DefaultTableModel) tbFunc.getModel();
        model.setNumRows(0);
        
        model.addRow(new Object[]{
            func.getNome(),
            func.getCpf(),
            func.getRegistro(),
            func.getCelular(),
            func.getEmail(),
            func.getCargo().getNome_cargo(),
            func.getSalario(),
            ativo
        });
        tbFunc.setModel(model);
    }
    
    private void carregaFuncionario(){
        listaFunc = (ArrayList<Funcionario>) funcionarioDAO.read();
        String ativo = "Inativo";
        DefaultTableModel model = (DefaultTableModel) tbFunc.getModel();
        model.setNumRows(0);
        
        for(Funcionario fun:listaFunc){            
            if(fun.isAtivo()){
                ativo =  "Ativo";
            }
            model.addRow(new Object[]{
                fun.getNome(),
                fun.getCpf(),
                fun.getRegistro(),
                fun.getCelular(),
                fun.getEmail(),
                fun.getCargo().getNome_cargo(),
                fun.getSalario(),
                ativo
            });
        }
        tbFunc.setModel(model);
    }

    private void deleta() {
        if(tfCPFFunc.getText().equals("___.___.___-__")){
            JOptionPane.showMessageDialog(rootPane, "Não foi possivel executar essa função");
        }else{
            dao.FuncionarioDAO.getInstance().delete(tfCPFFunc.getText());
            limpa();
        }
    }

    private void setMask() {
        tfCPFFunc.setFormatterFactory(Mascara.getCpfMask());
        tfCelularFunc.setFormatterFactory(Mascara.getCelMask());
        tfDnFunc.setFormatterFactory(Mascara.getDataMask());
        tfDrFunc.setFormatterFactory(Mascara.getDataMask());
        tfSalarioFunc.setFormatterFactory(Mascara.getValorMask());
        tfBuscarFunc.setFormatterFactory(Mascara.getCpfMask());

    }

    private void limpa() {
        tfNomeFunc.setText("");
        tfCPFFunc.setText("");
        tfCelularFunc.setText("");
        tfEmailFunc.setText("");
        tfDnFunc.setText("");
        tfDrFunc.setText("");
        tfSalarioFunc.setText("00,00");
    }

    private void update() {
        if (tfNomeFunc.getText().isEmpty() || tfCPFFunc.getText().isEmpty() || tfSalarioFunc.getText().isEmpty()
                || tfDnFunc.getText().isEmpty() || tfDrFunc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Existe algum campo vazio");
        } else {
            String nome = tfNomeFunc.getText();
            String cpf = tfCPFFunc.getText();
            String cel = tfCelularFunc.getText();
            String email = tfEmailFunc.getText();
            String data_nasc = tfDnFunc.getText();
            String data_registro = tfDrFunc.getText();
            Cargo cargo = null;
            cargo = (Cargo) cbCargo.getSelectedItem();
            double salario = Converte.textoToValue(tfSalarioFunc.getText());
            boolean Ativo = CheckAtivo.isSelected();
            Funcionario f = new Funcionario(cargo, Ativo, salario, nome, email, cpf, data_nasc, cel, data_registro);
            dao.FuncionarioDAO.getInstance().update(f);
            limpa();
        }

    }

    private void preencheCb() {
        CargoDAO dao = new CargoDAO();
        for (Cargo c : dao.read()) {
            cbCargo.addItem(c);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckAtivo;
    private javax.swing.JButton btAlterarFunc;
    private javax.swing.JButton btBuscarFunc;
    private javax.swing.JButton btDeletarFunc;
    private javax.swing.JButton btGravarFunc;
    private javax.swing.JButton btLimpaBusca;
    private javax.swing.JButton btNovo;
    private javax.swing.JComboBox<Object> cbCargo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCPFFunc;
    private javax.swing.JLabel lbCargp;
    private javax.swing.JLabel lbCelFunc;
    private javax.swing.JLabel lbDnFunc;
    private javax.swing.JLabel lbDrFunc;
    private javax.swing.JLabel lbEmailFunc;
    private javax.swing.JLabel lbNomeFunc;
    private javax.swing.JLabel lbSalarioFunc;
    private javax.swing.JLabel lbStatusFunc;
    private javax.swing.JTable tbFunc;
    private javax.swing.JFormattedTextField tfBuscarFunc;
    private javax.swing.JFormattedTextField tfCPFFunc;
    private javax.swing.JFormattedTextField tfCelularFunc;
    private javax.swing.JFormattedTextField tfDnFunc;
    private javax.swing.JFormattedTextField tfDrFunc;
    private javax.swing.JFormattedTextField tfEmailFunc;
    private javax.swing.JTextField tfNomeFunc;
    private javax.swing.JFormattedTextField tfSalarioFunc;
    // End of variables declaration//GEN-END:variables
}
