/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Produto;
import Model.Venda;
import Model.VendasProduto;
import dao.ProdutoDAO;
import dao.VendaDAO;
import dao.VendasProdutoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tegon Faria
 */
public class TelaVendas extends javax.swing.JFrame {
    Venda venda = new Venda();
    VendaDAO VendaDAO = new VendaDAO();
    ArrayList<Venda> listaVenda = new ArrayList<>();
    VendasProduto vendasProduto = new VendasProduto();
    VendasProdutoDAO vendasProdutoDAO = new VendasProdutoDAO();
    ArrayList<VendasProduto> listaVp = new ArrayList<>();
    Produto produto = new Produto();
    ProdutoDAO produtoDAO = new ProdutoDAO();
    ArrayList<Produto> listaProduto = new ArrayList<>();
    
    public TelaVendas() {
        initComponents();
        carregaVendas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenda = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tfCodVenda = new javax.swing.JTextField();
        tfCPFCliente = new javax.swing.JTextField();
        tfFunc = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");
        setResizable(false);

        tbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Venda", "Data Venda", "Funcionario", "CPF Cliente", "Desc.", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbVenda);
        if (tbVenda.getColumnModel().getColumnCount() > 0) {
            tbVenda.getColumnModel().getColumn(0).setMinWidth(90);
            tbVenda.getColumnModel().getColumn(0).setPreferredWidth(90);
            tbVenda.getColumnModel().getColumn(0).setMaxWidth(90);
            tbVenda.getColumnModel().getColumn(1).setMinWidth(90);
            tbVenda.getColumnModel().getColumn(1).setPreferredWidth(90);
            tbVenda.getColumnModel().getColumn(1).setMaxWidth(90);
            tbVenda.getColumnModel().getColumn(3).setMinWidth(85);
            tbVenda.getColumnModel().getColumn(3).setPreferredWidth(85);
            tbVenda.getColumnModel().getColumn(3).setMaxWidth(85);
            tbVenda.getColumnModel().getColumn(4).setMinWidth(45);
            tbVenda.getColumnModel().getColumn(4).setPreferredWidth(45);
            tbVenda.getColumnModel().getColumn(4).setMaxWidth(45);
            tbVenda.getColumnModel().getColumn(5).setMinWidth(90);
            tbVenda.getColumnModel().getColumn(5).setPreferredWidth(90);
            tbVenda.getColumnModel().getColumn(5).setMaxWidth(90);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendas\n"));

        tfCodVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodVendaActionPerformed(evt);
            }
        });

        tfCPFCliente.setEditable(false);

        tfFunc.setEditable(false);
        tfFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFuncActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel1.setText("Cod. Venda");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel2.setText("CPF Cliente");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel3.setText("Funcionario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(426, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodVendaActionPerformed
        venda = VendaDAO.find(Integer.parseInt(tfCodVenda.getText()));
        tfCPFCliente.setText(venda.getCliente().getCpf());
        tfFunc.setText(venda.getVendedor().getNome());
        buscaVendas();
    }//GEN-LAST:event_tfCodVendaActionPerformed

    private void tfFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFuncActionPerformed
        
    }//GEN-LAST:event_tfFuncActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try{
            int idVenda = Integer.parseInt(tfCodVenda.getText());
            listaVp = (ArrayList<VendasProduto>) vendasProdutoDAO.find(idVenda);

            for(VendasProduto v:listaVp){
                produto = produtoDAO.findById(v.getProduto());
                produto.setQuantidade(produto.getQuantidade() + v.getVenProdQtd());
                produtoDAO.update(produto);
            }

            vendasProdutoDAO.delete(idVenda);
            VendaDAO.delete(idVenda);
            carregaVendas();
            limpa();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(rootPane, "Não foi possivel realizar a função");
        }
        
    }//GEN-LAST:event_btExcluirActionPerformed
    
    private void carregaVendas(){
        DefaultTableModel model = (DefaultTableModel) tbVenda.getModel();
        listaVenda = (ArrayList<Venda>) VendaDAO.read();
        model.setNumRows(0);
        for(Venda v:listaVenda){
            model.addRow(new Object[]{
                v.getCodigo(),
                v.getData_venda(),
                v.getVendedor().getNome(),
                v.getCliente().getCpf(),
                v.getDesconto(),
                v.getValor_total()});
        }
        tbVenda.setModel(model);
    }
    
    private void buscaVendas(){
        DefaultTableModel model = (DefaultTableModel) tbVenda.getModel();
        venda = VendaDAO.find(Integer.parseInt(tfCodVenda.getText()));
        model.setNumRows(0);
        model.addRow(new Object[]{
            venda.getCodigo(),
            venda.getData_venda(),
            venda.getVendedor().getNome(),
            venda.getCliente().getCpf(),
            venda.getDesconto(),
            venda.getValor_total()});
            
        tbVenda.setModel(model);
    }
    
    private void limpa(){
       tfCPFCliente.setText("");
       tfCodVenda.setText("");
       tfFunc.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVenda;
    private javax.swing.JTextField tfCPFCliente;
    private javax.swing.JTextField tfCodVenda;
    private javax.swing.JTextField tfFunc;
    // End of variables declaration//GEN-END:variables
}
